"""add core domain tables"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '4301c213517b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('account_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('normalized_raw_name', sa.Text(), nullable=False),
    sa.Column('ancestor_context', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'normalized_raw_name', 'ancestor_context', name='uq_client_account_mapping_context')
    )
    op.create_index(op.f('ix_account_mappings_client_id'), 'account_mappings', ['client_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_client_id'), 'runs', ['client_id'], unique=False)
    op.create_table('taxonomies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomies_client_id'), 'taxonomies', ['client_id'], unique=False)
    op.create_table('run_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('ancestors', sa.JSON(), nullable=False),
    sa.Column('matched_code', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_line_items_run_id'), 'run_line_items', ['run_id'], unique=False)
    op.create_table('taxonomy_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxonomy_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_id', 'code', name='uq_taxonomy_entry_code')
    )
    op.create_index(op.f('ix_taxonomy_entries_taxonomy_id'), 'taxonomy_entries', ['taxonomy_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('chat_message', sa.Text(), nullable=True),
    sa.Column('resulting_code', sa.String(length=64), nullable=False),
    sa.Column('corrected_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['line_item_id'], ['run_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrections_line_item_id'), 'corrections', ['line_item_id'], unique=False)
    op.create_index(op.f('ix_corrections_run_id'), 'corrections', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corrections_run_id'), table_name='corrections')
    op.drop_index(op.f('ix_corrections_line_item_id'), table_name='corrections')
    op.drop_table('corrections')
    op.drop_index(op.f('ix_taxonomy_entries_taxonomy_id'), table_name='taxonomy_entries')
    op.drop_table('taxonomy_entries')
    op.drop_index(op.f('ix_run_line_items_run_id'), table_name='run_line_items')
    op.drop_table('run_line_items')
    op.drop_index(op.f('ix_taxonomies_client_id'), table_name='taxonomies')
    op.drop_table('taxonomies')
    op.drop_index(op.f('ix_runs_client_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_account_mappings_client_id'), table_name='account_mappings')
    op.drop_table('account_mappings')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###