"""add correction conflict tracking"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '898514e287f9'
down_revision: Union[str, None] = '4301c213517b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrections', sa.Column('previous_code', sa.String(length=64), nullable=True))
    op.add_column(
        'corrections',
        sa.Column('is_conflict', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrections', 'is_conflict')
    op.drop_column('corrections', 'previous_code')
    # ### end Alembic commands ###